### ISSUE TITLE
Dynamic rows with wysiwyg data

### ISSUE THREAD

**Issue by jasonkarlin12** [graschik/magento-2-admin-ui#7]
I'm trying to create an accordian widget to allow users to enter multiple rows with a title and rich html content. I updated the dynamicRows example to use a wysiwyg field for field_2 and I can save the data but I'm not sure how to decode that data to display.  In my widget class, I'm looping through and grabbing the data. Should I be using the getData method from AbstractWidget (which includes the call to decodeComponentValue? I'm not clear what the key/index values should be.  

`<?php
namespace TrumpOrg\Core\Block\Content\Widget;

use Magento\Widget\Block\BlockInterface;

class MarketingContentAccordian extends \Grasch\AdminUi\Block\Widget\AbstractWidget implements BlockInterface
{
    protected $_template = "content/widget/marketing-content-accordian.phtml";
    
    public function getAccordianData()
    {
        $accordian = Array();
        $accordianData = Array();

        $componentData = $this->getData('component_data')['dynamic_rows']['dynamic_rows'];
        foreach ($componentData as $row) {
            $accordianData['title'] = $row['title'];
            $accordianData['content'] = $row['wysiwyg'];

            $accordian[] = $accordianData;
        }

        return $accordian;
    }

}
`

**Comment by graschik** [comment]
@jasonkarlin12 could you provide me with the form xml file?

**Comment by jasonkarlin12** [comment]
`
<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <argument name="data" xsi:type="array">
        <item name="js_config" xsi:type="array">
            <item name="provider" xsi:type="string">accordian.accordian_data_source</item>
        </item>
    </argument>
    <settings>
        <namespace>accordian</namespace>
        <dataScope>data</dataScope>
        <deps>
            <dep>accordian.accordian_data_source</dep>
        </deps>
    </settings>
    <dataSource name="accordian_data_source" component="Magento_Ui/js/form/provider">
        <dataProvider class="Grasch\AdminUi\DataProvider\Widget\DataProvider" name="accordian_data_source" />
    </dataSource>
    <fieldset name="general">
        <settings>
            <label>Accordian Options</label>
            <collapsible>false</collapsible>
            <opened>true</opened>
        </settings>

        <dynamicRows name="dynamic_rows">
            <settings>
                <label translate="true">Dynamic Rows</label>
                <dataScope>dynamic_rows</dataScope>
                <addButtonLabel translate="true">Add Record</addButtonLabel>
                <additionalClasses>
                    <class name="admin__field-wide">true</class>
                </additionalClasses>
                <componentType>dynamicRows</componentType>
            </settings>
            <container name="record" component="Magento_Ui/js/dynamic-rows/record">
                <argument name="data" xsi:type="array">
                    <item name="config" xsi:type="array">
                        <item name="isTemplate" xsi:type="boolean">true</item>
                        <item name="is_collection" xsi:type="boolean">true</item>
                        <item name="componentType" xsi:type="string">container</item>
                    </item>
                </argument>
                <field name="title" formElement="input">
                    <argument name="data" xsi:type="array">
                        <item name="config" xsi:type="array">
                            <item name="fit" xsi:type="boolean">false</item>
                        </item>
                    </argument>
                    <settings>
                        <validation>
                            <rule name="required-entry" xsi:type="boolean">true</rule>
                        </validation>
                        <dataType>text</dataType>
                        <label>Title</label>
                    </settings>
                </field>

                <field name="content" template="ui/form/field" formElement="wysiwyg">
                    <argument name="data" xsi:type="array">
                        <item name="config" xsi:type="array">
                            <item name="wysiwygConfigData" xsi:type="array">
                                <item name="height" xsi:type="string">100px</item>
                                <item name="add_variables" xsi:type="boolean">true</item>
                                <item name="add_widgets" xsi:type="boolean">true</item>
                                <item name="add_images" xsi:type="boolean">true</item>
                                <item name="add_directives" xsi:type="boolean">true</item>
                            </item>
                        </item>
                    </argument>
                    <settings>
                        <validation>
                            <rule name="required-entry" xsi:type="boolean">true</rule>
                        </validation>
                        <label>Content</label>
                        <dataScope>wysiwyg</dataScope>
                    </settings>
                    <formElements>
                        <wysiwyg>
                            <settings>
                                <rows>8</rows>
                                <wysiwyg>true</wysiwyg>
                            </settings>
                        </wysiwyg>
                    </formElements>
                </field>
                <field name="position" component="Magento_Catalog/js/form/element/input" formElement="input">
                    <settings>
                        <visible>false</visible>
                    </settings>
                </field>
            </container>
        </dynamicRows>
    </fieldset>
</form>
`

**Comment by graschik** [comment]
@jasonkarlin12 this code works good for me 
```php
public function getAccordianData()
{
    $accordian = Array();
    $accordianData = Array();

    $componentData = $this->getData('component_data')['dynamic_rows']['dynamic_rows'];
    foreach ($componentData as $row) {
        $accordianData['title'] = $row['title'];
        $accordianData['content'] = $row['wysiwyg'];

        $accordian[] = $accordianData;
    }

    return $accordian;
}
```

**Comment by jasonkarlin12** [comment]
Sorry, wasn't clear. That code is working to get the data but the content is still encoded.  I'm trying to figure out how to decode the content.  What I get on the page looks like this

`
            <div class="marketing-content-accordian-title">title1</div>
        <div class="marketing-content-accordian-content">PHN0eWxlPiNodG1sLWJvZHkgW2RhdGEtcGItc3R5bGU9SVhXS1dER117anVzdGlmeS1jb250ZW50OmZsZXgtc3RhcnQ7ZGlzcGxheTpmbGV4O2ZsZXgtZGlyZWN0aW9uOmNvbHVtbjtiYWNrZ3JvdW5kLXBvc2l0aW9uOmxlZnQgdG9wO2JhY2tncm91bmQtc2l6ZTpjb3ZlcjtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1hdHRhY2htZW50OnNjcm9sbH08L3N0eWxlPjxkaXYgZGF0YS1jb250ZW50LXR5cGU9InJvdyIgZGF0YS1hcHBlYXJhbmNlPSJjb250YWluZWQiIGRhdGEtZWxlbWVudD0ibWFpbiI+PGRpdiBkYXRhLWVuYWJsZS1wYXJhbGxheD0iMCIgZGF0YS1wYXJhbGxheC1zcGVlZD0iMC41IiBkYXRhLWJhY2tncm91bmQtaW1hZ2VzPSJ7fSIgZGF0YS1iYWNrZ3JvdW5kLXR5cGU9ImltYWdlIiBkYXRhLXZpZGVvLWxvb3A9InRydWUiIGRhdGEtdmlkZW8tcGxheS1vbmx5LXZpc2libGU9InRydWUiIGRhdGEtdmlkZW8tbGF6eS1sb2FkPSJ0cnVlIiBkYXRhLXZpZGVvLWZhbGxiYWNrLXNyYz0iIiBkYXRhLWVsZW1lbnQ9ImlubmVyIiBkYXRhLXBiLXN0eWxlPSJJWFdLV0RHIj48ZGl2IGRhdGEtY29udGVudC10eXBlPSJ0ZXh0IiBkYXRhLWFwcGVhcmFuY2U9ImRlZmF1bHQiIGRhdGEtZWxlbWVudD0ibWFpbiI+PHA+Q29udGVudDE8L3A+PC9kaXY+PC9kaXY+PC9kaXY+</div>
            <div class="marketing-content-accordian-title">title2</div>
        <div class="marketing-content-accordian-content">PHN0eWxlPiNodG1sLWJvZHkgW2RhdGEtcGItc3R5bGU9WEJMNDFFMF17anVzdGlmeS1jb250ZW50OmZsZXgtc3RhcnQ7ZGlzcGxheTpmbGV4O2ZsZXgtZGlyZWN0aW9uOmNvbHVtbjtiYWNrZ3JvdW5kLXBvc2l0aW9uOmxlZnQgdG9wO2JhY2tncm91bmQtc2l6ZTpjb3ZlcjtiYWNrZ3JvdW5kLXJlcGVhdDpuby1yZXBlYXQ7YmFja2dyb3VuZC1hdHRhY2htZW50OnNjcm9sbH08L3N0eWxlPjxkaXYgZGF0YS1jb250ZW50LXR5cGU9InJvdyIgZGF0YS1hcHBlYXJhbmNlPSJjb250YWluZWQiIGRhdGEtZWxlbWVudD0ibWFpbiI+PGRpdiBkYXRhLWVuYWJsZS1wYXJhbGxheD0iMCIgZGF0YS1wYXJhbGxheC1zcGVlZD0iMC41IiBkYXRhLWJhY2tncm91bmQtaW1hZ2VzPSJ7fSIgZGF0YS1iYWNrZ3JvdW5kLXR5cGU9ImltYWdlIiBkYXRhLXZpZGVvLWxvb3A9InRydWUiIGRhdGEtdmlkZW8tcGxheS1vbmx5LXZpc2libGU9InRydWUiIGRhdGEtdmlkZW8tbGF6eS1sb2FkPSJ0cnVlIiBkYXRhLXZpZGVvLWZhbGxiYWNrLXNyYz0iIiBkYXRhLWVsZW1lbnQ9ImlubmVyIiBkYXRhLXBiLXN0eWxlPSJYQkw0MUUwIj48ZGl2IGRhdGEtY29udGVudC10eXBlPSJ0ZXh0IiBkYXRhLWFwcGVhcmFuY2U9ImRlZmF1bHQiIGRhdGEtZWxlbWVudD0ibWFpbiI+PHA+Q29udGVudDI8L3A+PC9kaXY+PC9kaXY+PC9kaXY+</div>
    `

**Comment by graschik** [comment]
@jasonkarlin12 try to use \Grasch\AdminUi\Model\Base64::decode method
this works for me
before decoding ```PHA+YXNrbG1kYWxza2RtbGFrc2Q8L3A+```
after decoding ```<p>asklmdalskdmlaksd</p>```

```php
public function getAccordianData()
{
    $accordian = Array();
    $accordianData = Array();

    $componentData = $this->getData('component_data')['dynamic_rows']['dynamic_rows'];
    foreach ($componentData as $row) {
        $accordianData['title'] = $row['title'];
        $accordianData['content'] = $this->base64->decode($row['wysiwyg']);

        $accordian[] = $accordianData;
    }

    return $accordian;
```

**Comment by jasonkarlin12** [comment]
When I try that, I get this error on the page.  Is there something else I need to add to the widget class?

`Error filtering template: Warning: Undefined property: TrumpOrg\Core\Block\Content\Widget\MarketingContentAccordian::$base64 in /home/developer/Sites/trump/app/code/TrumpOrg/Core/Block/Content/Widget/MarketingContentAccordian.php on line 17 `

**Comment by graschik** [comment]
@jasonkarlin12 have you added the base64 property to the constructor of the MarketingContentAccordian class?

**Comment by jasonkarlin12** [comment]
That worked now. Sorry, I'm still pretty new to PHP/Magento so I appreaciate you walking me through all that. I added the __construct and added a local Base64 and am now able to see the decoded value on the screen. Thanks so much!!
