### ISSUE TITLE
Issue with using regular widgets.

### ISSUE THREAD

**Issue by jeremiebarnes** [graschik/magento-2-admin-ui#8]
When trying to save widgets either custom or OOTB that don't use UI components, they are unable to be inserted due to a javascript error using Adobe Commerce 2.4.6-p5

Uncaught ReferenceError: form is not defined
    insertWidget http://localhost.test/static/version1715042648/adminhtml/Magento/spectrum/en_US/Grasch_AdminUi/js/wysiwyg/widget.js:535

**Comment by graschik** [comment]
@jeremiebarnes This has been fixed. Please update the module to version 1.0.4

**Comment by jeremiebarnes** [comment]
Thank you @graschik !
